version: "3.8"
services:
  mrss-feed-requests-cache:
    extends:
      file: ./docker-compose.dev.yml
      service: mrss-feed-requests-cache
  
  mrss-rabbitmq-broker:
    extends:
      file: ./docker-compose.dev.yml
      service: mrss-rabbitmq-broker

  mrss-mongo:
    extends:
      file: ./docker-compose.dev.yml
      service: mrss-mongo
  
  mrss-postgres-feed-requests:
    extends:
      file: ./docker-compose.dev.yml
      service: mrss-postgres-feed-requests
      
  mrss-postgres-user-feeds-service:
    extends:
      file: ./docker-compose.dev.yml
      service: mrss-postgres-user-feeds-service

  mrss-discord-rest-listener:
    extends:
      file: ./docker-compose.dev.yml
      service: mrss-discord-rest-listener
    build:
      context: services/discord-rest-listener
      dockerfile: Dockerfile
      target: prod
    command: ["node", "build/app.js"]

  mrss-feed-requests-service:
    extends:
      file: ./docker-compose.dev.yml
      service: mrss-feed-requests-service
    build:
      context: services/feed-requests
      dockerfile: Dockerfile
      target: prod
    command: ["node", "dist/main.js"]

  mrss-feed-requests-api:
    extends:
      file: ./docker-compose.dev.yml
      service: mrss-feed-requests-api
    build:
      context: services/feed-requests
      dockerfile: Dockerfile
      target: prod
    command: ["node", "dist/main.js"]

  mrss-feed-requests-db-migration:
    extends:
      file: ./docker-compose.dev.yml
      service: mrss-feed-requests-service
    build:
      context: services/feed-requests
      dockerfile: Dockerfile
      target: build
    command: "npm run migration:local:up"

  mrss-user-feeds-service:
    extends:
      file: ./docker-compose.dev.yml
      service: mrss-user-feeds-service
    build:
      context: services/user-feeds
      dockerfile: Dockerfile
      target: prod
    command: ["node", "dist/main.js"]

  mrss-user-feeds-db-migration:
    extends:
      file: ./docker-compose.dev.yml
      service: mrss-user-feeds-db-migration

  mrss-legacy-feed-bulk-converter-service:
    extends:
      file: ./docker-compose.dev.yml
      service: mrss-legacy-feed-bulk-converter-service
    build:
      context: services/backend-api
      dockerfile: dockerfiles/legacy-feed-bulk-converter/Dockerfile
      target: prod
    command: ["node", "dist/scripts/legacy-feed-bulk-converter.js"]

  mrss-schedule-emitter-service:
    extends:
      file: ./docker-compose.dev.yml
      service: mrss-schedule-emitter-service
    build:
      context: services/backend-api
      dockerfile: dockerfiles/schedule-emitter/Dockerfile
      target: prod
    command: ["node", "dist/scripts/schedule-emitter.js"]

  mrss-monolith:
    build:
      context: services/backend-api
      dockerfile: dockerfiles/web/mixed.Dockerfile
      target: prod
    restart: on-failure:3
    depends_on:
      - mrss-mongo
      - mrss-user-feeds-service
      - mrss-feed-requests-service
    ports:
      - "8000:8000"
    env_file:
      - ./.env.local
    environment:
      - BACKEND_API_NODE_ENV=local
      - BACKEND_API_PORT=8000
      - BACKEND_API_MONGODB_URI=mongodb://mrss-mongo:27017/rss
      - BACKEND_API_USER_FEEDS_API_HOST=http://mrss-user-feeds-service:5000
      - BACKEND_API_FEED_REQUESTS_API_HOST=http://mrss-feed-requests-api:5000
      - BACKEND_API_LOGIN_REDIRECT_URI=http://localhost:8000
      - BACKEND_API_DISCORD_REDIRECT_URI=http://localhost:8000/api/v1/discord/callback-v2
      - BACKEND_API_DEFAULT_REFRESH_RATE_MINUTES=0.1
      - BACKEND_API_DEFAULT_MAX_FEEDS=10
      - BACKEND_API_FEED_USER_AGENT=MonitoRSS
      - BACKEND_API_RABBITMQ_BROKER_URL=amqp://guest:guest@mrss-rabbitmq-broker:5672/
      - BACKEND_API_DEFAULT_MAX_USER_FEEDS=1
      - BACKEND_API_MAX_DAILY_ARTICLES_DEFAULT=50
      - BACKEND_API_USER_FEEDS_API_KEY=user-feeds-api-key
      - BACKEND_API_FEED_REQUESTS_API_KEY=feed-requests-api-key
    command: ["node", "dist/main.js"]
    networks:
      - monitorss-default


volumes:
  db-mongodb-data:
  db-feedrequests-postgres-data:
  db-user-feeds-postgres-data:
  cache-feed-requests:
  fs-s3-storage-data:
    driver: local

networks:
  monitorss-default:
    driver: bridge